/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as ApiPublicAccountDeleteRouteImport } from './routes/api/public/account/delete'
import { Route as ApiPublicCampusSearchRouteImport } from './routes/api/public/campus/search'
import { Route as ApiPublicCommunityActivityRouteImport } from './routes/api/public/community/activity'
import { Route as ApiPublicNotifyAppointmentRouteImport } from './routes/api/public/notify/appointment'
import { Route as ApiPublicVerifyCheckRouteImport } from './routes/api/public/verify/check'
import { Route as ApiPublicVerifyConfirmRouteImport } from './routes/api/public/verify/confirm'
import { Route as ApiPublicVerifyLinkRouteImport } from './routes/api/public/verify/link'
import { Route as ApiPublicVerifyLookupRouteImport } from './routes/api/public/verify/lookup'
import { Route as ApiPublicVerifySendRouteImport } from './routes/api/public/verify/send'
import { Route as ApiPublicVerifyStatusRouteImport } from './routes/api/public/verify/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountDeleteRoute = ApiPublicAccountDeleteRouteImport.update({
  id: '/api/public/account/delete',
  path: '/api/public/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCampusSearchRoute = ApiPublicCampusSearchRouteImport.update({
  id: '/api/public/campus/search',
  path: '/api/public/campus/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommunityActivityRoute =
  ApiPublicCommunityActivityRouteImport.update({
    id: '/api/public/community/activity',
    path: '/api/public/community/activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotifyAppointmentRoute =
  ApiPublicNotifyAppointmentRouteImport.update({
    id: '/api/public/notify/appointment',
    path: '/api/public/notify/appointment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVerifyCheckRoute = ApiPublicVerifyCheckRouteImport.update({
  id: '/api/public/verify/check',
  path: '/api/public/verify/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyConfirmRoute = ApiPublicVerifyConfirmRouteImport.update({
  id: '/api/public/verify/confirm',
  path: '/api/public/verify/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyLinkRoute = ApiPublicVerifyLinkRouteImport.update({
  id: '/api/public/verify/link',
  path: '/api/public/verify/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyLookupRoute = ApiPublicVerifyLookupRouteImport.update({
  id: '/api/public/verify/lookup',
  path: '/api/public/verify/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifySendRoute = ApiPublicVerifySendRouteImport.update({
  id: '/api/public/verify/send',
  path: '/api/public/verify/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyStatusRoute = ApiPublicVerifyStatusRouteImport.update({
  id: '/api/public/verify/status',
  path: '/api/public/verify/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/beta': typeof BetaRoute
  '/api/public/account/delete': typeof ApiPublicAccountDeleteRoute
  '/api/public/campus/search': typeof ApiPublicCampusSearchRoute
  '/api/public/community/activity': typeof ApiPublicCommunityActivityRoute
  '/api/public/notify/appointment': typeof ApiPublicNotifyAppointmentRoute
  '/api/public/verify/check': typeof ApiPublicVerifyCheckRoute
  '/api/public/verify/confirm': typeof ApiPublicVerifyConfirmRoute
  '/api/public/verify/link': typeof ApiPublicVerifyLinkRoute
  '/api/public/verify/lookup': typeof ApiPublicVerifyLookupRoute
  '/api/public/verify/send': typeof ApiPublicVerifySendRoute
  '/api/public/verify/status': typeof ApiPublicVerifyStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/beta': typeof BetaRoute
  '/api/public/account/delete': typeof ApiPublicAccountDeleteRoute
  '/api/public/campus/search': typeof ApiPublicCampusSearchRoute
  '/api/public/community/activity': typeof ApiPublicCommunityActivityRoute
  '/api/public/notify/appointment': typeof ApiPublicNotifyAppointmentRoute
  '/api/public/verify/check': typeof ApiPublicVerifyCheckRoute
  '/api/public/verify/confirm': typeof ApiPublicVerifyConfirmRoute
  '/api/public/verify/link': typeof ApiPublicVerifyLinkRoute
  '/api/public/verify/lookup': typeof ApiPublicVerifyLookupRoute
  '/api/public/verify/send': typeof ApiPublicVerifySendRoute
  '/api/public/verify/status': typeof ApiPublicVerifyStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/beta': typeof BetaRoute
  '/api/public/account/delete': typeof ApiPublicAccountDeleteRoute
  '/api/public/campus/search': typeof ApiPublicCampusSearchRoute
  '/api/public/community/activity': typeof ApiPublicCommunityActivityRoute
  '/api/public/notify/appointment': typeof ApiPublicNotifyAppointmentRoute
  '/api/public/verify/check': typeof ApiPublicVerifyCheckRoute
  '/api/public/verify/confirm': typeof ApiPublicVerifyConfirmRoute
  '/api/public/verify/link': typeof ApiPublicVerifyLinkRoute
  '/api/public/verify/lookup': typeof ApiPublicVerifyLookupRoute
  '/api/public/verify/send': typeof ApiPublicVerifySendRoute
  '/api/public/verify/status': typeof ApiPublicVerifyStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/beta'
    | '/api/public/account/delete'
    | '/api/public/campus/search'
    | '/api/public/community/activity'
    | '/api/public/notify/appointment'
    | '/api/public/verify/check'
    | '/api/public/verify/confirm'
    | '/api/public/verify/link'
    | '/api/public/verify/lookup'
    | '/api/public/verify/send'
    | '/api/public/verify/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/beta'
    | '/api/public/account/delete'
    | '/api/public/campus/search'
    | '/api/public/community/activity'
    | '/api/public/notify/appointment'
    | '/api/public/verify/check'
    | '/api/public/verify/confirm'
    | '/api/public/verify/link'
    | '/api/public/verify/lookup'
    | '/api/public/verify/send'
    | '/api/public/verify/status'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/beta'
    | '/api/public/account/delete'
    | '/api/public/campus/search'
    | '/api/public/community/activity'
    | '/api/public/notify/appointment'
    | '/api/public/verify/check'
    | '/api/public/verify/confirm'
    | '/api/public/verify/link'
    | '/api/public/verify/lookup'
    | '/api/public/verify/send'
    | '/api/public/verify/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BetaRoute: typeof BetaRoute
  ApiPublicAccountDeleteRoute: typeof ApiPublicAccountDeleteRoute
  ApiPublicCampusSearchRoute: typeof ApiPublicCampusSearchRoute
  ApiPublicCommunityActivityRoute: typeof ApiPublicCommunityActivityRoute
  ApiPublicNotifyAppointmentRoute: typeof ApiPublicNotifyAppointmentRoute
  ApiPublicVerifyCheckRoute: typeof ApiPublicVerifyCheckRoute
  ApiPublicVerifyConfirmRoute: typeof ApiPublicVerifyConfirmRoute
  ApiPublicVerifyLinkRoute: typeof ApiPublicVerifyLinkRoute
  ApiPublicVerifyLookupRoute: typeof ApiPublicVerifyLookupRoute
  ApiPublicVerifySendRoute: typeof ApiPublicVerifySendRoute
  ApiPublicVerifyStatusRoute: typeof ApiPublicVerifyStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account/delete': {
      id: '/api/public/account/delete'
      path: '/api/public/account/delete'
      fullPath: '/api/public/account/delete'
      preLoaderRoute: typeof ApiPublicAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/campus/search': {
      id: '/api/public/campus/search'
      path: '/api/public/campus/search'
      fullPath: '/api/public/campus/search'
      preLoaderRoute: typeof ApiPublicCampusSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/community/activity': {
      id: '/api/public/community/activity'
      path: '/api/public/community/activity'
      fullPath: '/api/public/community/activity'
      preLoaderRoute: typeof ApiPublicCommunityActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify/appointment': {
      id: '/api/public/notify/appointment'
      path: '/api/public/notify/appointment'
      fullPath: '/api/public/notify/appointment'
      preLoaderRoute: typeof ApiPublicNotifyAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/check': {
      id: '/api/public/verify/check'
      path: '/api/public/verify/check'
      fullPath: '/api/public/verify/check'
      preLoaderRoute: typeof ApiPublicVerifyCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/confirm': {
      id: '/api/public/verify/confirm'
      path: '/api/public/verify/confirm'
      fullPath: '/api/public/verify/confirm'
      preLoaderRoute: typeof ApiPublicVerifyConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/link': {
      id: '/api/public/verify/link'
      path: '/api/public/verify/link'
      fullPath: '/api/public/verify/link'
      preLoaderRoute: typeof ApiPublicVerifyLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/lookup': {
      id: '/api/public/verify/lookup'
      path: '/api/public/verify/lookup'
      fullPath: '/api/public/verify/lookup'
      preLoaderRoute: typeof ApiPublicVerifyLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/send': {
      id: '/api/public/verify/send'
      path: '/api/public/verify/send'
      fullPath: '/api/public/verify/send'
      preLoaderRoute: typeof ApiPublicVerifySendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/status': {
      id: '/api/public/verify/status'
      path: '/api/public/verify/status'
      fullPath: '/api/public/verify/status'
      preLoaderRoute: typeof ApiPublicVerifyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BetaRoute: BetaRoute,
  ApiPublicAccountDeleteRoute: ApiPublicAccountDeleteRoute,
  ApiPublicCampusSearchRoute: ApiPublicCampusSearchRoute,
  ApiPublicCommunityActivityRoute: ApiPublicCommunityActivityRoute,
  ApiPublicNotifyAppointmentRoute: ApiPublicNotifyAppointmentRoute,
  ApiPublicVerifyCheckRoute: ApiPublicVerifyCheckRoute,
  ApiPublicVerifyConfirmRoute: ApiPublicVerifyConfirmRoute,
  ApiPublicVerifyLinkRoute: ApiPublicVerifyLinkRoute,
  ApiPublicVerifyLookupRoute: ApiPublicVerifyLookupRoute,
  ApiPublicVerifySendRoute: ApiPublicVerifySendRoute,
  ApiPublicVerifyStatusRoute: ApiPublicVerifyStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
