/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicVerifyCheckRouteImport } from './routes/api/public/verify/check'
import { Route as ApiPublicVerifySendRouteImport } from './routes/api/public/verify/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyCheckRoute = ApiPublicVerifyCheckRouteImport.update({
  id: '/api/public/verify/check',
  path: '/api/public/verify/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifySendRoute = ApiPublicVerifySendRouteImport.update({
  id: '/api/public/verify/send',
  path: '/api/public/verify/send',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/verify/check': typeof ApiPublicVerifyCheckRoute
  '/api/public/verify/send': typeof ApiPublicVerifySendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/verify/check': typeof ApiPublicVerifyCheckRoute
  '/api/public/verify/send': typeof ApiPublicVerifySendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/verify/check': typeof ApiPublicVerifyCheckRoute
  '/api/public/verify/send': typeof ApiPublicVerifySendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/verify/check' | '/api/public/verify/send'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/verify/check' | '/api/public/verify/send'
  id: '__root__' | '/' | '/api/public/verify/check' | '/api/public/verify/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicVerifyCheckRoute: typeof ApiPublicVerifyCheckRoute
  ApiPublicVerifySendRoute: typeof ApiPublicVerifySendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/check': {
      id: '/api/public/verify/check'
      path: '/api/public/verify/check'
      fullPath: '/api/public/verify/check'
      preLoaderRoute: typeof ApiPublicVerifyCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/send': {
      id: '/api/public/verify/send'
      path: '/api/public/verify/send'
      fullPath: '/api/public/verify/send'
      preLoaderRoute: typeof ApiPublicVerifySendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicVerifyCheckRoute: ApiPublicVerifyCheckRoute,
  ApiPublicVerifySendRoute: ApiPublicVerifySendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
